
(() => {

  settingWords = {};

  // Exlusion de ces termes dans l'affichage des Hn de la page web (headings)
  settingWords.exclusesWords = [
    "🟥",
    ":",
    "(",
    ")",
    "[",
    "]",
    "?",
    "!",
    "&",
    "a",
    "à",
    "à laquelle",
    "afficher",
    "afin",
    "ainsi",
    "alentours",
    "aller",
    'apporte',
    'apportent',
    "après",
    "au",
    "aucun",
    "aucune",
    "aucunes",
    "aucuns",
    "auquel",
    "autrui",
    "aussi",
    "aux",
    "auxquelles",
    "auxquels",
    "avec",
    'besoins',
    'besoin',
    "button",
    "c'est",
    "c’est",
    "ça",
    "ce",
    "ceci",
    "cela",
    "celle",
    "celle-ci",
    "celle-là",
    "celles",
    "celles-ci",
    "celles-là",
    "celui",
    "celui-ci",
    "celui-là",
    "cette",
    "certaine",
    "certaines",
    "certains",
    "ces",
    "ceux",
    "ceux-ci",
    "ceux-là",
    "chacun",
    "chacune",
    "comme",
    "commencé",
    "d'",
    "d’",
    "d’aucun",
    "d’aucuns",
    "d'autres",
    "d'un",
    "dans",
    "de",
    "de laquelle",
    "depuis",
    "des",
    "désormais",
    "desquelles",
    "desquels",
    "dont",
    "du",
    "duquel",
    "effet",
    "également",
    "elle",
    "elles",
    "en",
    "encore",
    "Encore",
    "et",
    "être",
    "etc",
    "est",
    "eux",
    "faire",
    'grâce',
    "il",
    "ils",
    "ici",
    "je",
    "l'",
    "l’",
    "l'autre",
    "l'un",
    "l'une",
    "la",
    "la leur",
    "la même",
    "la mienne",
    "la nôtre",
    "la sienne",
    "la tienne",
    "la vôtre",
    "laquelle",
    "le",
    "le leur",
    "le même",
    "le mien",
    "le nôtre",
    "le sien",
    "le tien",
    "le vôtre",
    "lequel",
    "les",
    "les autres",
    "les leurs",
    "les mêmes",
    "les miennes",
    "les miens",
    "les nôtres",
    "les siennes",
    "les siens",
    "les tiennes",
    "les tiens",
    "les unes",
    "les uns",
    "les vôtres",
    "lesquelles",
    "lesquels",
    "leur",
    "lui",
    "m’",
    'mais',
    "me",
    "moi",
    "non",
    "nos",
    "Nos",
    "notre",
    "nous",
    "nul",
    "nulle",
    "nulles",
    "nuls",
    "on",
    "ou",
    "où",
    "ouvrir",
    "par",
    "pas",
    "personne",
    "peut",
    "plus",
    "plusieurs",
    "pour",
    "près",
    "prêt",
    "qu'est-ce",
    "que",
    "quelles",
    "Quelles",
    "quelqu'un",
    "quelqu'une",
    "quelque chose",
    "quelques unes",
    "quelques uns",
    "quels",
    "Quels",
    "qui",
    "quiconque",
    "quoi",
    "rien",
    "sa",
    "se",
    "selon",
    "ses",
    "soi",
    "son",
    "sont",
    "sur",
    "t’",
    "te",
    "tel",
    "telle",
    "telles",
    "tels",
    "toi",
    "tous",
    "tout",
    "toute",
    "toutes",
    "très",
    "tu",
    "un",
    "un autre",
    "une",
    "une autre",
    "utilisons",
    "vers",
    "vos",
    "votre",
    "vous",
    "y"
  ];

  //Classes exclues dans la récupération des mots de la page web
  settingWords.excludedClasses = [
    "vc_btn3-container",
    "dmCustomWidget",
    "slide-text",
    "vc_btn3",
    "pj-prolive-hc",
    "dmButtonLink",
    "proliveContainer",
    'vc_mappy-map',
    "dmFooterContainer",
    "widgets_wrapper",
    "footer_action",
    "footer_copy",
    "cloned",
    "SOMS_avis-container"
  ];
  //Noeuds exclus dans la récupération des mots de la page web

  settingWords.excludedNodes = [
    "iframe",
    "button",
    "textarea",
    "script",
    "style",
    "source",
    "video",
    "picture",
    "form",
    "code",
    "frameset",
    "noframes",
    "map",
    "area",
    "figcaption",
    "figure",
    "svg",
    "nav",
    "menu",
    "menuitem",
    "footer",
    "noscript",
    "embed",
    "param",
    "rs-module-wrap",
    "rs-layer-wrap",
    "head",
    "header"
  ];

  // Liste des mots à exclure
  settingWords.replaceWords = [
    "Button",
    "Afficher davantage",
    "John Doe",
    "City skyline",
    "Photo By:",
    "Birthday Sparks",
    "Fashion Magazine",
    "Blurred Lines",
    "Photo by:",
    "Learn More"
  ];
})()