settingWords={};

settingWords.replaceWords = [
    "Button",
    "Afficher davantage",
    "John Doe",
    "City skyline",
    "Photo By:",
    "Birthday Sparks",
    "Fashion Magazine",
    "Blurred Lines",
    "Photo by:"
  ];
  settingWords.exclusesWords = [
    "&",
    "?",
    ":",
    "je",
    "me",
    "m’",
    "moi",
    "tu",
    "te",
    "t’",
    "l'",
    "toi",
    "par",
    "nous",
    "vous",
    "il",
    "de",
    "des",
    "du",
    "ces",
    "ses",
    "près",
    "pour",
    "vers",
    "selon",
    "vos",
    "et",
    "aux",
    "d'",
    "au",
    "ou",
    "où",
    "votre",
    "notre",
    "à",
    "a",
    "sur",
    "dans",
    "alentours",
    "elle",
    "ils",
    "elles",
    "se",
    "en",
    "y",
    "le",
    "la",
    "l’",
    "les",
    "lui",
    "soi",
    "leur",
    "eux",
    "lui",
    "leur",
    "celui",
    "celui-ci",
    "celui-là",
    "celle",
    "celle-ci",
    "celle-là",
    "ceux",
    "ceux-ci",
    "ceux-là",
    "celles",
    "celles-ci",
    "celles-là",
    "ce",
    "ceci",
    "cela",
    "ça",
    "le mien",
    "le tien",
    "le sien",
    "la mienne",
    "la tienne",
    "la sienne",
    "les miens",
    "les tiens",
    "les siens",
    "les miennes",
    "les tiennes",
    "les siennes",
    "le nôtre",
    "le vôtre",
    "le leur",
    "la nôtre",
    "la vôtre",
    "la leur",
    "les nôtres",
    "les vôtres",
    "les leurs",
    "qui",
    "que",
    "quoi",
    "dont",
    "où",
    "lequel",
    "auquel",
    "duquel",
    "laquelle",
    "à laquelle",
    "de laquelle",
    "lesquels",
    "auxquels",
    "desquels",
    "lesquelles",
    "auxquelles",
    "desquelles",
    "qui",
    "que",
    "quoi",
    "qu'est-ce",
    "lequel",
    "auquel",
    "duquel",
    "laquelle",
    "à laquelle",
    "de laquelle",
    "lesquels",
    "auxquels",
    "desquels",
    "lesquelles",
    "auxquelles",
    "desquelles",
    "on",
    "tout",
    "un",
    "une",
    "l'un",
    "l'une",
    "les uns",
    "les unes",
    "un autre",
    "une autre",
    "d'autres",
    "d'un",
    "l'autre",
    "les autres",
    "aucun",
    "aucune",
    "aucuns",
    "aucunes",
    "certains",
    "certaine",
    "certains",
    "certaines",
    "tel",
    "telle",
    "tels",
    "telles",
    "tout",
    "toute",
    "tous",
    "toutes",
    "le même",
    "la même",
    "les mêmes",
    "nul",
    "nulle",
    "nuls",
    "nulles",
    "quelqu'un",
    "quelqu'une",
    "quelques uns",
    "quelques unes",
    "personne (aucun)",
    "autrui",
    "quiconque",
    "d’aucun",
    "autrui",
    "on",
    "personne",
    "quelque chose",
    "quiconque",
    "rien",
    "chacun",
    "chacune",
    "plus",
    "plusieurs",
    "d’aucuns",
    "Quelles",
    "quelles",
    "quelles",
    "sont",
    "Quels",
    "quels",
    "encore",
    "Encore",
    "Nos",
    "nos",
  ];